#!/bin/sh
cp ./target/armv7-unknown-linux-gnueabihf/release/pi_off /usr/bin/pi_off
chmod 755 /usr/bin/pi_off

cp ./systemd/pi_off.service /etc/systemd/system/pi_off.service
chmod 644 /etc/systemd/system/pi_off.service

systemctl enable pi_off
systemctl start pi_off